### PR TITLE
java-openliberty: Notify of the removal of quick-start-security.xml

### PR DESCRIPTION
**Pull request by uberskigeek**
### Checklist:

- [x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).

- [x] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).

- [x] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stacks-overview.md#stack-structure).

### Modifying an existing stack:

- [x] Updated the stack version in `stack.yaml`

### Contributing a new stack:

- Describe how application dependencies are managed:

### CODE REVIEW

**Comment by uberskigeek** [comment]
fixes #756

**Comment by scottkurz** [comment]
@skoh7645 @Kamran64 ready to merge 

For rel notes: "Updated stack description" 

Thanks

**Comment by neeraj-laad** [comment]
@skoh7645 @Kamran64 please can. you see if the description still fits and looks on on Appsodt website / stacks page here - https://appsody.dev/stacks/

I'm worried this is too long.

**Comment by skoh7645** [comment]
@neeraj-laad LGTM - the stack linter limits the stack description to 70 characters so it looks good on the website
Screenshot 2020-04-15 at 12 45 22

**Pull request merged**
