### PR TITLE
java-openliberty: run as non-root user

### PR DESCRIPTION
**Pull request by uberskigeek**
### Checklist:

- [x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).

- [x] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).

- [x] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stacks-overview.md#stack-structure).

### Modifying an existing stack:

- [x] Updated the stack version in `stack.yaml`

### Contributing a new stack:

- Describe how application dependencies are managed:

- Explain how Appsody file watcher is utilized:

- Describe other Appsody environment variables defined by the stack image:

- Describe any limitations and known issues:

### CODE REVIEW

**Comment by uberskigeek** [comment]
#607

**Comment by groeges** [comment]
Have you tried running this on a Linux system using a local user that doesn't have a uid/gid that matches the values that you have set in the Dockerfile and Dockerfile-stack for the java_user/java_group.

**Comment by Kamran64** [comment]
@uberskigeek @scottkurz - Can we close this now? I thought it was added in 0.2.0.

**Comment by scottkurz** [comment]
Yes this was merged..closing

**Pull request closed without merging**
