### PR TITLE
[python-flask] Ensure liveness port is exposed

### LINKED ISSUE #461: python-flask deploy endpoint not reachable
**Describe the bug**
Trying an `appsody deploy` of the python-flask stack and the endpoint is not reachable

**To Reproduce**
1. setup and configure docker desktop with kubernetes
2. `mkdir python-flask`
3. `cd python-flask`
4. `appsody init python-flask`
5. `appsody deploy -v`

**Expected behavior**
Expected to get the usual endpoint webpage

**Actual behaviour**
The endpoint URL given `http://localhost:31867` is not reachable
```
[Docker] Successfully built 4911c055ac6c
[Docker] Successfully tagged dev.local/python-flask:latest
Built docker image dev.local/python-flask
Using applicationImage of: dev.local/python-flask
Attempting to apply resource in Kubernetes ...
Running command: kubectl apply -f app-deploy.yaml --namespace test
Deployment succeeded.
Appsody Deployment name is: python-flask
Running command: kubectl get rt python-flask -o jsonpath="{.status.url}" --namespace test
Attempting to get resource from Kubernetes ...
Running command: kubectl get route python-flask -o jsonpath={.status.ingress[0].host} --namespace test
Attempting to get resource from Kubernetes ...
Running command: kubectl get svc python-flask -o jsonpath=http://{.status.loadBalancer.ingress[0].hostname}:{.spec.ports[0].nodePort} --namespace test
Deployed project running at http://localhost:31867
```

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] mac, tried windows10 also

**If applicable please specify:**
 - CLI version: 0.4.8
 - Stack you are using (including the version): python-flask

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by henrynash**
Expose the liveness port in the application docker file (it was only being exposed in the stack docker file). Without this,  k8s  would consider the pod to be dead.

Fixes #461

### CODE REVIEW

**Comment by henrynash** [comment]
@Kamran64 Which k8s are you deploying to?

**Comment by Kamran64** [comment]
@henrynash I was using the Docker for Desktop version of k8s.

**Comment by henrynash** [comment]
> @henrynash I was using the Docker for Desktop version of k8s.

Me too! Hmm. I think there is still something wrong here, since I too have from time to time seen something that I can't explain in terms of not connecting. Let me dig further

**Comment by Kamran64** [comment]
It's happened to me several times before as well so I wasn't sure if it was an issue with the stack or a problem on my end. I'll try again using Minikube and see if I get a different result.

**Comment by henrynash** [comment]
> It's happened to me several times before as well so I wasn't sure if it was an issue with the stack or a problem on my end. I'll try again using Minikube and see if I get a different result.

So I am on the trail. I know WHAT is going wrong, I just can't explain WHY. First, my original fix is wrong.....we don't want to expose 5678...since that isn't what the python server is listening on. In fact, what IS happening is that somehow appsody deploy is thinking that the main APPSODY_PORT is 5678 (and not 8080 that is exposed)....which is why both the liveness is failing AND the regular url is not being served. I just can't explain WHY appsody deploy is doing this right now....

**Comment by henrynash** [comment]
Ok, I think I have this resolved. appsody deploy creates that app-config.yaml PORTS based on the stack image NOT the Dockerfile for the application! This seems wrong to me, and I have raised a separate issue for this.

Since I did not have an ENV PORT=8080 statement in Dockerfile-stack, it picked one of the ports (the wrong one!).

**Pull request merged**
