### PR TITLE
nodejs-express: run as node user rather than root

### PR DESCRIPTION
**Pull request by Kamran64**
### Checklist:

- [x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).

- [x] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).

- [x] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stacks-overview.md#stack-structure).

### Modifying an existing stack:

- [x] Updated the stack version in `stack.yaml`

To be merged after https://github.com/appsody/stacks/pull/604. #604 will run the nodejs stack as node user which should be propagated to the express stack.

### CODE REVIEW

**Comment by sam-github** [comment]
Running as the `node` user in the container and writing to the host fs via a volume map will fail, because the `node` user is unknown to the host.

You'll see this when you run on Linux:
```
cloud-node/ex-bug % appsody run
Running development environment...
Using local cache for image dev.local/appsody/nodejs-express:0.4
Running command: docker run --rm -p 3000:3000 -p 9229:9229 --name ex-bug-dev -v /home/sam/w/cloud-node/ex-bug/:/project/user-app -v ex-bug-deps:/project/user-app/node_modules
 -v appsody-controller-0.3.3:/.appsody -t --entrypoint /.appsody/appsody-controller dev.local/appsody/nodejs-express:0.4 --mode=run
[Container] Running APPSODY_PREP command: npm install --prefix user-app && npm audit fix --prefix user-app
[Container] [..................] | rollbackFailedOptional: verb npm-session 559532f983cnpm WARN checkPermissions Missing write access to /project/user-app/node_modules/debugl
og
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules
[Container] npm ERR! code EACCES
[Container] npm ERR! syscall access
[Container] npm ERR! path /project/user-app/node_modules/debuglog
[Container] npm ERR! errno -13
[Container] npm ERR! Error: EACCES: permission denied, access '/project/user-app/node_modules/debuglog'
[Container] npm ERR!  [Error: EACCES: permission denied, access '/project/user-app/node_modules/debuglog'] {
[Container] npm ERR!   stack: "Error: EACCES: permission denied, access '/project/user-app/node_modules/debuglog'",
[Container] npm ERR!   errno: -13,
[Container] npm ERR!   code: 'EACCES',
[Container] npm ERR!   syscall: 'access',
[Container] npm ERR!   path: '/project/user-app/node_modules/debuglog'
[Container] npm ERR! }
[Container] npm ERR! 
[Container] npm ERR! The operation was rejected by your operating system.
[Container] npm ERR! It is likely you do not have the permissions to access this file as the current user
[Container] npm ERR! 
[Container] npm ERR! If you believe this might be a permissions issue, please double-check the
[Container] npm ERR! permissions of the file and its containing directories, or try running
[Container] npm ERR! the command again as root/Administrator.
[Container] 
[Container] npm ERR! A complete log of this run can be found in:
[Container] npm ERR!     /home/node/.npm/_logs/2020-01-10T16_56_37_964Z-debug.log
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 243
[Error] Error in 'appsody run': exit status 1
```

**Comment by sam-github** [comment]
Also, does this have any relationship to https://github.com/appsody/stacks/issues/593, `APPSODY_USER_RUN_AS_LOCAL`?

**Comment by Kamran64** [comment]
@sam-github - I decided to use the `node` user here since there's one already established. True, we could create a new user and have that across the other stacks too although several stacks already handle this in their own way e.g. the Spring boot stack creates `java-user`.

Thanks for the approval. I've messed around with setting `APPSODY_USER_RUN_AS_LOCAL` but I'm still seeing the `user-app` created as root (but at least now the rest of the contents in `/project` are owned by the `node` user).

**Comment by sam-github** [comment]
@andrewhughes101 Do you have time to manually confirm whether this fixes https://github.com/appsody/stacks/issues/566?

**Comment by sam-github** [comment]
I confirmed that #604 fixes #566

**Comment by groeges** [comment]
@Kamran64 I tried  running `appsody stack validate` using this PR source on my Linux (ubuntu) box and got failures executing the `run` and `test` actions using the `scaffold` template. The `simple` template passed.  The error I was getting for the scaffold template was:
```
**************************************************************************
Running appsody run against stack:dev.local/nodejs-expresstemplate: scaffold
**************************************************************************
[/usr/bin/appsody run --name testRunContainer]
Running development environment...
Using local cache for image dev.local/appsody/nodejs-express:0.4
Running command: docker run --rm -p 3000:3000 -p 9229:9229 --name testRunContainer -v /home/groeges/.appsody/stacks/validating-nodejs-express/:/project/user-app -v validating-nodejs-express-deps:/project/user-app/node_modules -v appsody-controller-0.3.4:/.appsody -t --entrypoint /.appsody/appsody-controller dev.local/appsody/nodejs-express:0.4 --mode=run
[Container] Running APPSODY_PREP command: npm install --prefix user-app && npm audit fix --prefix user-app
about to run appsody ps
[/usr/bin/appsody ps]
CONTAINER ID	NAME            	IMAGE                               	PORTS                                         	STATUS
3ea9530fb0cf	testRunContainer	dev.local/appsody/nodejs-express:0.4	0.0.0.0:3000->3000/tcp, 0.0.0.0:9229->9229/tcp	Up Less than a second
appsody ps contains correct container name
npm WARN checkPermissions Missing write access to /project/user-app/node_modules/camelcase
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/is-buffer
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/cliui
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/yargs/node_modules/ansi-regex
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/yargs/node_modules/strip-ansi
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/yargs/node_modules/string-width
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/yargs
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/yargs-unparser/node_modules
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/yargs/node_modules
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/flat
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/mocha
[Container] npm WARN checkPermissions Missing write access to /project/user-app/node_modules/yargs-parser
[Container] npm ERR! code EACCES
[Container] npm ERR! syscall access
[Container] npm ERR! path /project/user-app/node_modules/camelcase
[Container] npm ERR! errno -13
[Container] npm ERR! Error: EACCES: permission denied, access '/project/user-app/node_modules/camelcase'
[Container] npm ERR!  [Error: EACCES: permission denied, access '/project/user-app/node_modules/camelcase'] {
[Container] npm ERR!   stack: "Error: EACCES: permission denied, access '/project/user-app/node_modules/camelcase'",
[Container] npm ERR!   errno: -13,
[Container] npm ERR!   code: 'EACCES',
[Container] npm ERR!   syscall: 'access',
[Container] npm ERR!   path: '/project/user-app/node_modules/camelcase'
[Container] npm ERR! }
[Container] npm ERR!
[Container] npm ERR! The operation was rejected by your operating system.
[Container] npm ERR! It is likely you do not have the permissions to access this file as the current user
[Container] npm ERR!
[Container] npm ERR! If you believe this might be a permissions issue, please double-check the
[Container] npm ERR! permissions of the file and its containing directories, or try running
[Container] npm ERR! the command again as root/Administrator.
[Container]
[Container] npm ERR! A complete log of this run can be found in:
[Container] npm ERR!     /home/node_user/.npm/_logs/2020-02-24T11_58_40_832Z-debug.log
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 243
about to run appsody ps
[/usr/bin/appsody ps]
CONTAINER ID	NAME            	IMAGE                               	PORTS                                         	STATUS
3ea9530fb0cf	testRunContainer	dev.local/appsody/nodejs-express:0.4	0.0.0.0:3000->3000/tcp, 0.0.0.0:9229->9229/tcp	Up 2 seconds
appsody ps contains correct container name
[Error] Error in 'appsody run': exit status 1
[Error] Appsody run failed
[Error] exit status 1
```

**Comment by groeges** [comment]
Hmmmm, however running this on a different Linux machine, all ran successfully.

**Comment by groeges** [comment]
OK, think I have figured out why one of my Linux machines is failing. Basically I had a docker volume that had been created earlier, probably when testing the nodejs-express stack for other non-root scenarios. This volume had data setup in it that was accessible only as root. So when we were running the non-root build of the nodejs-express stack it failed as it could not access these files. Deleting the volume and running the `appsody stack validate` commands again allowed everything to work.

So, all in all this PR looks good.   However, the issue with the docker volume persisting is an issue and this needs to be resolved. Will raise an issue relating to docker volume usage.

**Comment by sam-github** [comment]
Needs to be synced with the other PRs: #589 #604 #624

**Comment by Kamran64** [comment]
Let's close this PR for now. We need to come up with a basis for how we should approach this problem. It looks like the changes to https://github.com/appsody/stacks/pull/624 might be the way forward. We can reopen this later once the implementation details are finalised.

**Pull request closed without merging**
