### PR TITLE
Issue 857: add maven settings.xml and update liberty version

### LINKED ISSUE #857: Add maven settings.xml to java-openliberty stack
To provide a consistent view of all java based stacks the java-openliberty stack should implement a maven settings.xml.

### PR DESCRIPTION
**Pull request by uberskigeek**
### Checklist:

- [x ] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).

- [ x] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).

- [x ] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stacks-overview.md#stack-structure).

### Modifying an existing stack:

- [x ] Updated the stack version in `stack.yaml`

### Contributing a new stack:

- Describe how application dependencies are managed:

- Explain how Appsody file watcher is utilized:

- Describe other Appsody environment variables defined by the stack image:

- Describe any limitations and known issues:

### Related Issues:

Fixes #857

### CODE REVIEW

**Review by scottkurz — DISMISSED** [review]
LGTM.  Just update the version in the README

**Review by scottkurz — APPROVED** [review]
LGTM

**Review by scottkurz — APPROVED** [review]
LGTM

**Review by neeraj-laad — APPROVED** [review]
LGTM

**Pull request merged**
