### PR TITLE
Update Spring Boot on Liberty Stack to base on Open Liberty stack.

### PR DESCRIPTION
**Pull request by BarDweller**
### Checklist:

- [x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).

- [x] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).

- [x] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stacks-overview.md#stack-structure).

### Modifying an existing stack:

- [x] Updated the stack version in `stack.yaml`

Rebase of the stack from the Microprofile stack to the Open Liberty stack.

This required switching from a jar based deploy, to a war based to allow use of the Open Liberty stack dev mode. As a breaking change, the minor version of this stack bumps from 0.1 to 0.2. 

Stack remains experimental for now.

### CODE REVIEW

**Comment by skoh7645** [comment]
@BarDweller When I pulled this down to test it, I got a build failure during `appsody run`:
Screenshot 2020-04-16 at 14 28 44
I noticed there is a similar build failure in the travis build for `appsody test` even though the build passed, see [here](https://travis-ci.com/github/appsody/stacks/builds/160252234#L3824).

**Comment by BarDweller** [comment]
I'll have a look at this today.. it was working locally.. it's possible that I already have something in place that causes it to avoid the issue.

**Comment by scottkurz** [comment]
> 
> 
> We caught a mistake here in `appsody test`: #790 .. fixing it now:

Sent you:  https://github.com/BarDweller/stacks/pull/3

**Comment by neeraj-laad** [comment]
Closing due to inactivity. Please re-open the PR if this is still something we want to add.

**Pull request closed without merging**
