### PR TITLE
extend timeout; simplify log files

### PR DESCRIPTION
**Pull request by ebullient**
### Checklist:

- [X] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).

- [X] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).

Break appsody stack commands into three:  lint, package, validate (no-lint, no-package)
Extend travis timeout, use CI_WAIT_FOR (travis_wait) consistently
Use in-built travis log
Remove verbose flag (this will be better once appsody CLI brings in fix for verbose flags in stack package)
Remove a dangling Travis reference

### CODE REVIEW

**Comment by groeges** [comment]
@ebullient If we are changing the way we use CI_WAIT_FOR and using the built-in travis log, do we also want to change the code that generates the ngnix image?

**Comment by groeges** [comment]
OK, I re-ran the Travis build job and all worked OK this time around.

**Comment by ebullient** [comment]
> OK, I re-ran the Travis build job and all worked OK this time around.

This will work even better after the PR I made for the appsody CLI goes in (to drop use of -v in appsody stack commands): https://github.com/appsody/appsody/pull/816

That makes the output much less chatty. I can change the output for nginx, too, if you prefer. That one is the least interesting. ;)

**Comment by groeges** [comment]
@ebullient As the `travis wait` outputs the logs once complete how does the changes you have made stop the issue with exceeding the max log size. My latest build (https://travis-ci.com/appsody/stacks/builds/141406829) failed as it DID exceed the log size.
```
[Docker] Downloading from central: https://repo.maven.apache.org/maven2/io/openliberty/features/com.ibm.websphere.appserver.javax.annotation-1.3/19.0.0.8/com.ibm.websphere.appserver.javax.annotation-1.3-19.0.0.8.esa
Progress (4): 2.1/3.2 MB | 1.9/3.2 MB | 1.4/4.3 MB | 0.9/4.
The job exceeded the maximum log length, and has been terminated.
```

**Comment by ebullient** [comment]
> @ebullient As the `travis wait` outputs the logs once complete how does the changes you have made stop the issue with exceeding the max log size. My latest build (https://travis-ci.com/appsody/stacks/builds/141406829) failed as it DID exceed the log size.
> 
> ```
> [Docker] Downloading from central: https://repo.maven.apache.org/maven2/io/openliberty/features/com.ibm.websphere.appserver.javax.annotation-1.3/19.0.0.8/com.ibm.websphere.appserver.javax.annotation-1.3-19.0.0.8.esa
> Progress (4): 2.1/3.2 MB | 1.9/3.2 MB | 1.4/4.3 MB | 0.9/4.
> The job exceeded the maximum log length, and has been terminated.
> ```

It doesn't. It walks back some of the changes I made to handle that because you wanted to see the office always. ;) SOO. I will now put some of those back, as you see why I did what I did before. ;)

**Comment by ebullient** [comment]
Including in #559

**Pull request closed without merging**
