### PR TITLE
Updated Quarkus templates to match the 1.3.2.Final version of the source Quickstarts

### PR DESCRIPTION
**Pull request by paulrobinson**
The two templates in the Quarkus stack are based on quickstarts from https://github.com/quarkusio/quarkus-quickstarts. These Quickstarts are released in lockstep with Quarkus and are only designed (and tested) to work with the corresponding Quarkus version. Therefore, we should ensure that the templates in the stack, match their source as closely as possible.

In particular the:

`default` template is based on https://github.com/quarkusio/quarkus-quickstarts/tree/1.3.2.Final/getting-started.
`kafka` template is based on https://github.com/quarkusio/quarkus-quickstarts/tree/1.3.2.Final/kafka-quickstart

*Notice* The links above go to the `1.3.2.Final` version of the code, not `master`.

When updating the Quarkus version of the stack, it's important that the templates are also updated. This is a manual task, and is made easier (and less error-prone) if there are fewer diffs compared to the quickstarts.

This PR updates the templates to match, as closely as possible, the 1.3.2.Final quickstarts linked above.

Some changes may seem petty (whitespace and version downgrades). However, I think it will be much easier to maintain this duplication if we keep the differences to just those that must be there. If there's something wrong with the code, I think we should fix it in the Quickstart first.

Here's a summary of the diffs after these changes to better align the two code basis:

## Default

```
Only in /Users/paul/dev/quarkus-quickstarts/getting-started: .dockerignore
Only in /Users/paul/dev/quarkus-quickstarts/getting-started: .gitignore
Only in /Users/paul/dev/quarkus-quickstarts/getting-started: .mvn
Only in /Users/paul/dev/quarkus-quickstarts/getting-started: .s2i
Only in .: .vscode
Only in /Users/paul/dev/quarkus-quickstarts/getting-started: README.md
diff -r ./pom.xml /Users/paul/dev/quarkus-quickstarts/getting-started/pom.xml
5,10d4
<     <parent>
<         <groupId>dev.appsody</groupId>
<         <artifactId>quarkus</artifactId>
<         <version>[0.3,0.4)</version>
<     </parent>
<
14a9,33
>     <properties>
>         <quarkus-plugin.version>1.3.2.Final</quarkus-plugin.version>
>         <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
>         <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
>         <quarkus.platform.version>1.3.2.Final</quarkus.platform.version>
>         <compiler-plugin.version>3.8.1</compiler-plugin.version>
>         <surefire-plugin.version>2.22.1</surefire-plugin.version>
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>         <maven.compiler.source>1.8</maven.compiler.source>
>         <maven.compiler.target>1.8</maven.compiler.target>
>         <maven.compiler.parameters>true</maven.compiler.parameters>
>     </properties>
>
>     <dependencyManagement>
>         <dependencies>
>             <dependency>
>                 <groupId>${quarkus.platform.group-id}</groupId>
>                 <artifactId>${quarkus.platform.artifact-id}</artifactId>
>                 <version>${quarkus.platform.version}</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
>         </dependencies>
>     </dependencyManagement>
>
Only in /Users/paul/dev/quarkus-quickstarts/getting-started/src/main: docker
Only in /Users/paul/dev/quarkus-quickstarts/getting-started/src/main/java/org/acme: getting
Only in ./src/main/java/org/acme: quickstart
Only in ./src/main: main.iml
Only in /Users/paul/dev/quarkus-quickstarts/getting-started/src/test/java/org/acme: getting
Only in ./src/test/java/org/acme: quickstart
Only in ./src/test: test.iml
Only in ./src/test: test4.iml
```

## Kafka

```
Only in /Users/paul/dev/quarkus-quickstarts/kafka-quickstart/: .dockerignore
Only in /Users/paul/dev/quarkus-quickstarts/kafka-quickstart/: .gitignore
Only in /Users/paul/dev/quarkus-quickstarts/kafka-quickstart/: .mvn
Only in .: .vscode
Only in /Users/paul/dev/quarkus-quickstarts/kafka-quickstart/: README.md
diff -r ./docker-compose.yaml /Users/paul/dev/quarkus-quickstarts/kafka-quickstart/docker-compose.yaml
28c28
<       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
---
>       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
30a31
>
diff -r ./pom.xml /Users/paul/dev/quarkus-quickstarts/kafka-quickstart/pom.xml
5,11d4
<
<   <parent>
<     <groupId>dev.appsody</groupId>
<     <artifactId>quarkus</artifactId>
<     <version>[0.3,0.4)</version>
<   </parent>
<
15c8,28
<
---
>   <properties>
>     <surefire-plugin.version>2.22.1</surefire-plugin.version>
>     <quarkus-plugin.version>1.3.2.Final</quarkus-plugin.version>
>     <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
>     <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
>     <quarkus.platform.version>1.3.2.Final</quarkus.platform.version>
>     <maven.compiler.source>1.8</maven.compiler.source>
>     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>     <maven.compiler.target>1.8</maven.compiler.target>
>   </properties>
>   <dependencyManagement>
>     <dependencies>
>       <dependency>
>         <groupId>${quarkus.platform.group-id}</groupId>
>         <artifactId>${quarkus.platform.artifact-id}</artifactId>
>         <version>${quarkus.platform.version}</version>
>         <type>pom</type>
>         <scope>import</scope>
>       </dependency>
>     </dependencies>
>   </dependencyManagement>
Only in /Users/paul/dev/quarkus-quickstarts/kafka-quickstart/src/main: docker
Only in /Users/paul/dev/quarkus-quickstarts/kafka-quickstart/src/main/resources/META-INF/resources: index.html
Only in /Users/paul/dev/quarkus-quickstarts/kafka-quickstart/src: test
```

I think the above diffs are the ones we want and can't be avoided.

### CODE REVIEW

**Comment by paulrobinson** [comment]
This seems to be failing for an unrelated reason:

```FAILED: Test for stack:java-openliberty template:kafka```

I was looking at other PRs to see if they were also failing, and I noticed that the PR only seems to be testing the modified stack in the "Validate Summary Start" section. So it seems to me like the build is incorrectly using the openliberty stack (which also has a Karka template), instead of the Quarkus one.

**Comment by paulrobinson** [comment]
Actually, I see that on a successful PR run that multiple groups of tests are ran, but I'm still confused about which ones are picked. 

See: https://github.com/appsody/stacks/pull/783 which modifies Quarkus. 

Look in this log for the run: https://api.travis-ci.com/v3/job/324274275/log.txt

Notice these sections:

```
@@@@@@@@@@@@@@@ Validate Summary Start @@@@@@@@@@@@@@@@
PASSED: Init for stack:java-openliberty template:default
PASSED: Run for stack:java-openliberty template:default
PASSED: Test for stack:java-openliberty template:default
PASSED: Build for stack:java-openliberty template:default
Total PASSED: 4
Total FAILED: 0
@@@@@@@@@@@@@@@  Validate Summary End  @@@@@@@@@@@@@@@@
```

```
@@@@@@@@@@@@@@@ Validate Summary Start @@@@@@@@@@@@@@@@
PASSED: Init for stack:java-spring-boot2 template:kafka
PASSED: Run for stack:java-spring-boot2 template:kafka
PASSED: Test for stack:java-spring-boot2 template:kafka
PASSED: Build for stack:java-spring-boot2 template:kafka
PASSED: Init for stack:java-spring-boot2 template:kotlin
PASSED: Run for stack:java-spring-boot2 template:kotlin
PASSED: Test for stack:java-spring-boot2 template:kotlin
PASSED: Build for stack:java-spring-boot2 template:kotlin
PASSED: Init for stack:java-spring-boot2 template:default
PASSED: Run for stack:java-spring-boot2 template:default
PASSED: Test for stack:java-spring-boot2 template:default
PASSED: Build for stack:java-spring-boot2 template:default
Total PASSED: 12
Total FAILED: 0
@@@@@@@@@@@@@@@  Validate Summary End  @@@@@@@@@@@@@@@@
```

```@@@@@@@@@@@@@@@ Validate Summary Start @@@@@@@@@@@@@@@@
PASSED: Init for stack:nodejs-express template:simple
PASSED: Run for stack:nodejs-express template:simple
PASSED: Test for stack:nodejs-express template:simple
PASSED: Build for stack:nodejs-express template:simple
PASSED: Init for stack:nodejs-express template:scaffold
PASSED: Run for stack:nodejs-express template:scaffold
PASSED: Test for stack:nodejs-express template:scaffold
PASSED: Build for stack:nodejs-express template:scaffold
Total PASSED: 8
Total FAILED: 0
@@@@@@@@@@@@@@@  Validate Summary End  @@@@@@@@@@@@@@@@
```

So I'm confused now. I think the Kafka templates could be missing due to https://github.com/appsody/stacks/pull/783 being out of date. But I still don't understand why the Quarkus tests are missing, or why the Open Liberty ones are failing this PR.

**Comment by Kamran64** [comment]
@paulrobinson - The CI scripts will only run against the stack changed if there has been a version bump in the `stack.yaml`. Otherwise we fall back to testing against several default stacks (open liberty being one of them). If you bump the version, this PR should pass (or at least run against Quarkus) :)

**Comment by paulrobinson** [comment]
Aha! thanks.

Should we be worried that it's failing the Open liberty test?

**Comment by Kamran64** [comment]
Yeah, that issue's being tracked here: https://github.com/appsody/stacks/issues/799 - It's a symptom of the kafka template being merged (appsody test requires extra options).

**Pull request merged**
