### PR TITLE
Add monitoring to deploy yaml

### PR DESCRIPTION
**Pull request by BarDweller**
### Checklist:

- [x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).

- [x] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).

- [x] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stack-structure.md).

### Modifying an existing stack:

- [x] Updated the stack version in `stack.yaml`

Adds monitoring for Spring Boot 2 Java stack via Appsody Operator.
Adds required `timeoutSeconds` field for knative validation.

### Related Issues:

#391 
#313 
#441

### CODE REVIEW

**Comment by BarDweller** [comment]
I did bump the stack version.. it would seem the reason my bump is insufficient, is that you created #490 and made one part of the change you had requested as part of #441. 

Why did you do this? You raised #441, and it was being taken care of, yet you've now used an older pr to deliver a change that you'd requested as part of #441. 

If #490 didn't exist, this PR would have been fine.

**Comment by Kamran64** [comment]
@BarDweller - So I didn't actually create #490 (and didn't realise that it had even been raised/merged until reviewing your PR #491). Yes, the initial issue covered both the `timeoutSeconds` change and service monitoring support but we weren't aware that it was even being worked on since the issue is almost one month old. Although we agreed it would be best to leave the service monitoring support to the stack maintainers themselves, the `timeoutSeconds` fix was becoming more critical, see: https://github.com/kabanero-io/collections/issues/174 and therefore we resolved this.

**Comment by BarDweller** [comment]
@Kamran64 @neeraj-laad 
Agreed that #441 was old, and that I should have self-assigned it, but this wasn't handled well...

#441 existed, and was _still open_. It still (even now) requests that change. 
#490 was delivered against the parent of that task #391, while #441 was still open.

This was done without any update to #441 asking for status, or indicating that the item needed to be split for priority. This was also done without any contact via the listed stack maintainer who knew this work was underway. 

This calls into question stack ownership, when you say "we agreed it would be best to leave the service monitoring support to the stack maintainers themselves", who were the parties to this agreement? did it include the stack maintainers? how was this communicated, and where are the details documented?

This is a public project, and having the rug pulled from under stack maintainers by decisions made unilaterally without discussion is less than ideal.

**Comment by Kamran64** [comment]
I made an initial PR: https://github.com/appsody/stacks/pull/401 to implement service monitoring support for Spring Boot on Liberty. At this time, I admit I poorly tested it and so decided to close that and the other PR's implementing the change for further testing (which I then reopened and merged later for all relevant stacks bar Sb + Sb with Lib). I raised separate issues: https://github.com/appsody/stacks/issues/441 and https://github.com/appsody/stacks/issues/442 to add this for Spring Boot and Spring Boot on Liberty as I was told the implementation was inappropriate for the stacks (which I agree, at the time they were). After raising that issue, I mentioned you in a comment to ask if you were happy to tackle the implementation. As I received no response, I decided not to revisit work here. 

I agree, maybe more communication would have been important and in hindsight I should have followed up to keep you updated. Also, I agree maybe this should have been split into two separate issues to avoid the conflicts.

**Comment by BarDweller** [comment]
Fixed the merge for timeOutSeconds, updated stack maintainers list.

**Pull request merged**
