### PR TITLE
feat: add a Swift stack

### PR DESCRIPTION
**Pull request by ianpartridge**
Add a Swift stack. This provides a "Hello World" Swift application which builds and runs on Swift 5.

TODO: sort out `swift/image/project/Dockerfile` - it's probably not right.

### CODE REVIEW

**Comment by neeraj-laad** [comment]
@ianpartridge Thank you for your contribution, we really appreciate this. 

We will start reviewing this shortly.

**Comment by neeraj-laad** [comment]
@ianpartridge  Can you please review and sign our CLA.

**Comment by ianpartridge** [comment]
Done!

**Comment by seabaylea** [comment]
Is this now ready to merge?

**Comment by seabaylea** [comment]
Is there anything stopping this from being merged?

**Comment by mhamwala** [comment]
reviewed and tested:
- [x] appsody run 
- [x] appsody test
- [ ] appsody debug (no debug cmd provided)
- [x] appsody build
- [ ] appsody deploy (having a bit of trouble with KNative)

**Comment by seabaylea** [comment]
> [ ] appsody debug (no debug cmd provided)

There isn't really a good mechanism for doing remote debug in Swift, which is why this isn't enabled - I have some thoughts on how we might do this but its not worth holding on the PR for it.

> Hello world message appears in the terminal and changes are reflected but when I hit localhost:8080 when the container is up it doesn't respond with anything..

This is the same as for the base `nodejs` Stack - the stack and template don't contain a web framework (the assumption is that you'll bring your own as part of your application).  The template, as it is today, will print "Hello World" to the console.

**Comment by mhamwala** [comment]
Ahh i see, we should update the README as it says 
> This launches a Docker container that continuously re-builds and re-runs your project, exposing it on port `8080`.

**Comment by mhamwala** [comment]
We could make the README clearer by adding something this or similar:

This launches a Docker container that continuously re-builds and re-runs your project. It also exposes port 8080, to allow you to bring your own web application and use it with this stack.

3. You should see a message printed on the console:

    ```Hello, world!```

**Comment by ianpartridge** [comment]
I'm out today - feel free to push whatever you need to move this forward.

**Pull request merged**
