### PR TITLE
Update Vert.x and vmp versions

### PR DESCRIPTION
**Pull request by rdruss**
### Checklist:

- [x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).

- [ ] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).

- [ ] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stack-structure.md).

### Modifying an existing stack:

- [ ] Updated the stack version in `stack.yaml`

### Contributing a new stack:

- Describe how application dependencies are managed:

- Explain how Appsody file watcher is utilized:

- Describe other Appsody environment variables defined by the stack image:

- Describe any limitations and known issues:

### CODE REVIEW

**Comment by Kamran64** [comment]
I'm also noticing the travis build isn't picking up the changes you've made and therefore falling back to building backup stacks rather than Vert.x with your changes on top. Will do some investigating...

**Comment by rdruss** [comment]
The pom.xml using a version range from 0.1-0.2 and thus should incorporate the updated stack version.

**Comment by Kamran64** [comment]
@rdruss - How about the parent `pom.xml` in `image/project/pom.xml`?

**Comment by neeraj-laad** [comment]
@rdruss Please, can you review and sign our CLA.

**Comment by edewit** [comment]
:+1:

**Comment by richardfontana** [comment]
@neeraj-laad @rdruss is a Red Hat employee and created this contribution in the scope of his employment at Red Hat, making Red Hat the owner of all original intellectual property (copyrights and patent rights) inherent in this contribution. Having acquired Red Hat, IBM now owns this intellectual property through its ownership of Red Hat. Therefore, why should @rdruss (or Red Hat) have to sign an IBM CLA? It would in effect constitute IBM granting a meaningless license to itself. Do non-Red-Hat IBM employees who contribute to this project sign the CLA? 

BTW our understanding is that IBM is moving away from use of CLAs for open source projects in favor of the [DCO](https://developercertificate.org).

**Comment by sympatheticmoose** [comment]
@richardfontana @rdruss I understand your point, but even IBMers are asked to sign the CLA; Appsody is an open source project and contributions from any individual are to be treated in the same way. The project is currently using the IBM CLA, but should this be donated to an open foundation we would look to change that.

**Comment by richardfontana** [comment]
> @richardfontana @rdruss I understand your point, but even IBMers are asked to sign the CLA; Appsody is an open source project and contributions from any individual are to be treated in the same way. The project is currently using the IBM CLA, but should this be donated to an open foundation we would look to change that.

@sympatheticmoose Okay, that is interesting and helpful to know. I will just take a quick closer look at the CLA and then follow up with @rdruss

**Comment by Kamran64** [comment]
@richardfontana @rdruss - Any updates on this? I think this would be a nice QoL change to go in.

**Comment by Kamran64** [comment]
Closing this for now as the CLA hasn't been signed.

**Comment by richardfontana** [comment]
@Kamran64 I have now notified @rdruss that he can sign this CLA and have also whitelisted it for Red Hat employees generally on our internal list of upstream contributor agreements.

**Pull request closed without merging**
