### PR TITLE
kotlin-spring-boot2: Add a Kotlin Spring Boot 2 stack

### PR DESCRIPTION
**Pull request by pushkarnk**
### Checklist:

- [x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).

- [ ] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).

- [ ] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stack-structure.md).

### Modifying an existing stack:

- [ ] Updated the stack version in `stack.yaml`

### Contributing a new stack:

- Describe how application dependencies are managed:

- Explain how Appsody file watcher is utilized:

- Describe other Appsody environment variables defined by the stack image:

- Describe any limitations and known issues:

### Related Issues:

I've been trying to get Kotlin working with Spring Boot 2 on Appsody. Currently the patch is largely a copy of the java-spring-boot2 stack with some Kotlin specific additions to `Dockerfiles-stack` and `image/project/appsody-boot2-pom.xml`.

Though I did get a hello world app working, this is largely WIP. Also, I must admit I'm unsure if this is the right way to add Kotlin with Spring Boot 2 support. Hence a draft PR for now.

### CODE REVIEW

**Comment by pushkarnk** [comment]
Because I have no experience with Sprint Boot, I had some issues to get the `kotlin-maven-plugin` hooked into the build. But was able to get it included using some trial and error. Here's the [stdout](https://gist.github.com/pushkarnk/aa1b7a1147b94b17cec31e4478fb2d9c) for the `appsody run`.

**Comment by neeraj-laad** [comment]
@ebullient Given you are the maintainer of the java-spring-boot2 stack, you might want to chime in here.

**Comment by ebullient** [comment]
Y, I'll have a look to make sure this is ok. I am not sure we need an entirely different stack.

**Comment by pushkarnk** [comment]
This PR is on `pushkarnk/stack`s master branch. I wanted to change the branch (to make it easier to update the PR). Opened #101 . Closing this one. Thanks.

**Pull request closed without merging**
