### PR TITLE
[java-microprofile] Add javametrics as a dev only dependency

### PR DESCRIPTION
**Pull request by seabaylea**
This adds Javametrics-dash as a dev only dependency as part of the stack. This both provides developers with a build-in performance view, and enables the Eclipse Codewind IDE project to do application monitoring and performance testing the of the application during development.

The approach to providing the Javametrics dashboard during development only is as follows:
* Provide a pom-dev.xml file that installs the dependencies as installs them into the server which is only run in Dockerfile-stack, and not in the production Dockerfile.
* Provide a server-dev.xml that adds the necessary features that is only copied into the config dropins the Dockerfile-stack, and not in the production Dockerfile.

This pattern can be extended if there's further capabilities that we want to provide only during development.

### CODE REVIEW

**Comment by neeraj-laad** [comment]
@Emily-Jiang Would appreciate your feedback on this.

**Comment by Emily-Jiang** [comment]
@seabaylea I have 2 comments
1. java-metrics feature for dev: I am not aware of how popular to have this low level java-metrics in dev. I think this info might just be useful to performance team. I don't think Jen is interested in this. If you think some developers might need it, I think it might fit in well to have this as a guide.
2. In pushing for dev-prod parity, I think it is not very useful for dev to have one tool while Prod having another tool to view different info. I think it is better to use MicroProfile metrics and have Prometheus and/or Grafana accessible to the Dev.

**Comment by nastacio** [comment]
@seabaylea and @Emily-Jiang , this is also a matter of consistency across stacks when working with Codewind.

We ran into this during a workshop and writing guides, and pulled the PR into a forked repo just to showcase the functionality.

**Comment by csantanapr** [comment]
I just hit this problem
Using Cloud Pak Apps stack for microprofile I got the impression that codewind is something to leverage in both java and nodejs stacks, using the App Monitor and Perf Dasboard launchers in codewind.

nodejs works fine but in java-microfile I hit the problem and opened an issue here 
https://github.com/eclipse/codewind-java-profiler/issues/8

**Comment by ianpartridge** [comment]
I've rebased this PR so it no longer conflicts with `master`. It needs re-review by the stack owners.

@Emily-Jiang @gcharters @BarDweller @neeraj-laad please take a look

**Comment by ianpartridge** [comment]
@ yeekangc too

**Comment by gcharters** [comment]
I think this should be merged (or an updated version of it if the stack has changed since it was created) as without this capability the stack is not usable in Eclipse Codewind.  I consider this a tactical workaround and believe Codewind should be using the /metrics (e.g. MicroProfile metrics) endpoint from stacks that provide it.

**Comment by Kamran64** [comment]
Just tested this and it works i.e I can get the Javametrics dashboard endpoint - However, I'll leave the approval to one of the reviewers mentioned above ^

**Comment by Emily-Jiang** [comment]
This PR can be merged with the following agreement:

- This is a temp workaround. The ultimate solution should rely on MicroProfile Metrics. This PR does not demonstrate ecosystem nor the programming model.

- This PR should be removed once https://bigblue.aha.io/features/MC-156 is in place. 
I abstain from the voting.

**Comment by ianpartridge** [comment]
@Emily-Jiang I edited your comment to remove the reference to an internal link. This is a public open source project.

**Comment by yeekangc** [comment]
+1 to what Graham and Emily said.  This is a tactical solution and Codewind should use /metrics down the road.

**Comment by ianpartridge** [comment]
@Kamran64 any update on the testing?

**Comment by Kamran64** [comment]
@ianpartridge - @neeraj-laad and I took another look earlier. For some reason the command `'-javaagent:resources/javametrics-agent.jar'` fails only on `appsody test` but not on `run` and `debug`. We think this could probably be removed from `APPSODY_TEST` env in the Dockerfile-stack though.

**Pull request merged**
